--18/02/2025
--EXPLORANDO BANCO DE DADOS VENDAS

SELECT * FROM Customers

--FORNECEDORES
SELECT * FROM Suppliers

-- PEDIDOS DE VENDA
SELECT * FROM Orders

-- MOSTRE TODOS OS PRODUTOS JA VENDIDOS PARA O BRAZIL
-- COLUNAS : CODIGO DO PRODUTO, NOME DO PRODUTO,
-- ORDERNE POR NOME DO PRODUTO

-- O COMANDO DISTINCT NÃO TRARA LINHAS DUPLICADAS
SELECT DISTINCT PROD.ProductID AS CODIGO, PROD.ProductName AS PRODUTO
FROM Products PROD
INNER JOIN [Order Details] OD ON OD.ProductID = PROD.ProductID
INNER JOIN Orders P ON  P.OrderID = OD.OrderID
WHERE 
     P.ShipCountry = 'BRAZIL'
ORDER BY PRODUTO

-- MOSTRE A QUANTIDADE VENDIDA, POR PRODUTO, DE TODOS OS PRODUTOS ENVIADOS 
-- PARA O BRAZIL

SELECT PROD.ProductID AS CODIGO,
       PROD.ProductName AS PRODUTO,
       SUM (OD.Quantity) AS QTD
FROM Products PROD
INNER JOIN [Order Details] OD ON OD.ProductID = PROD.ProductID
INNER JOIN Orders P ON  P.OrderID = OD.OrderID
WHERE 
     P.ShipCountry = 'BRAZIL'
     GROUP BY PROD.ProductID,
     PROD.ProductName
ORDER BY PRODUTO

--GROUP BY TEM QUE USAR OS PRIMEIROS CAMPOS QUE ESTAO NO SELECT

-- MOSTRE A QUANTIDADE DE PRODUTOS FORNECIDA POR FORNECEDOR
-- COLUNAS: CÓDIGO DO PRODUTO, NOME DO PRODUTO, NOME DO FORNECEDOR, QUANTIDADE VENDIDA
-- EX: 001 | QUEIJO MINAS | LATICINIOS SENAI | 1200

SELECT PROD.ProductID CODIGO,
  PROD.ProductName AS NOME_PRODUTO,
  FORNEC.CompanyName, SUM (OD.Quantity) AS QTD_VENDIDA
FROM Products PROD
INNER JOIN Suppliers FORNEC ON FORNEC.SupplierID = PROD.SupplierID
INNER JOIN [Order Details] OD ON OD.ProductID = PROD.ProductID
GROUP BY PROD.ProductID,
         PROD.ProductName,
         FORNEC.CompanyName
ORDER BY FORNEC.CompanyName

-- CRIE UMA CONSULTA QUE MOSTRE AS VENDAS GERAIS POR PAÍS
-- COLUNAS :  DATA DA VENDA,PEDIDO, VENDEDOR, CLIENTE, CIDADE, REGIAO, PAÍS,
-- VALOR TOTAL DA VENDA

SELECT O.OrderDate AS DATA_VENDA, O.OrderID AS PEDIDO,
CONCAT(F.FirstName, '', F.LastName) AS VENDEDOR,
O.ShipName AS CLIENTE, 
O.ShipCity AS CIDADE,
ISNULL ( O.ShipRegion, 'N/A') AS REGIAO,
O.ShipCountry PAIS,
ROUND(SUM((OD.Quantity * OD.UnitPrice) * (1 - OD.Discount)), 2) AS TOTAL_VENDA
FROM Orders O
INNER JOIN Employees F ON F.EmployeeID = O.EmployeeID
INNER JOIN [Order Details] OD ON OD.OrderID = O.OrderID
GROUP BY O.OrderDate,O.OrderID,CONCAT(F.FirstName, '', F.LastName),
O.ShipName,
O.ShipCity,
ISNULL ( O.ShipRegion, 'N/A'),
O.ShipCountry
ORDER BY TOTAL_VENDA

-- CONCAT AGRUPA COLUNAS 
-- ISNULL TROCA O VALOR DO CAMPO QUE ESTA VAZIO OU COALESCE

-- MOSTRE O TOTAL VENDIDO PARA CADA CIDADE
-- COLUNAS: NOME DA CIDADE, NOME DO PAÍS, TOTAL VENDIDO
--EX: SAO PAULO | BRASIL | 150000

SELECT O.ShipCity AS CIDADE,
O.ShipCountry AS PAÍS,
ROUND(SUM((OD.Quantity * OD.UnitPrice) * (1 - OD.Discount)),2) AS TOTAL_VENDA
FROM Orders O
INNER JOIN [Order Details] OD ON OD.OrderID = O.OrderID
GROUP BY 
O.ShipCity,O.ShipCountry
ORDER BY 
PAÍS, TOTAL_VENDA DESC

-- CRIE UMA CONSULTA QUE MOSTRE O PRODUTO MAIS VENDIDO POR PAÍS
-- EXEMPLO: ARGENTINA | VINHO | 120000

-- RANQUEAMENTO DE REGISTROS E SUBCONSULTA

SELECT SUB_CONSULTA.PAIS, SUB_CONSULTA.NOME_PRODUTO, SUB_CONSULTA.TOTAL_VENDA
FROM
(
SELECT O.ShipCountry PAIS, 
       PROD.ProductName NOME_PRODUTO,
ROUND(SUM((OD.Quantity * OD.UnitPrice) * (1 - OD.Discount)),2) AS TOTAL_VENDA,
       -- CRIANDO RANKING ATRAVÉS DA FUNÇÃO ROW_NUMBER():
       ROW_NUMBER()OVER (PARTITION BY O.ShipCountry ORDER BY
       ROUND(SUM((OD.Quantity * OD.UnitPrice) * (1 - OD.Discount)),2) DESC) AS RANKING
FROM Orders O 
INNER JOIN [Order Details] OD ON OD.OrderID = O.OrderID
INNER JOIN Products PROD ON PROD.ProductID = OD.ProductID
GROUP BY
         O.ShipCountry,
         PROD.ProductName
) AS SUB_CONSULTA
WHERE SUB_CONSULTA.RANKING = 1 --AND
--      SUB_CONSULTA.PAIS NOT IN  (SELECT Country FROM Customers WHERE Country LIKE 'A%')
ORDER BY SUB_CONSULTA.PAIS

-- CTES - COMMON TABLE EXPRESSIONS

WITH RANKING AS
(
SELECT O.ShipCountry PAIS, 
       PROD.ProductName NOME_PRODUTO,
ROUND(SUM((OD.Quantity * OD.UnitPrice) * (1 - OD.Discount)),2) AS TOTAL_VENDA,
       -- CRIANDO RANKING ATRAVÉS DA FUNÇÃO ROW_NUMBER():
       ROW_NUMBER()OVER (PARTITION BY O.ShipCountry ORDER BY
       ROUND(SUM((OD.Quantity * OD.UnitPrice) * (1 - OD.Discount)),2) DESC) AS RANKING
FROM Orders O 
INNER JOIN [Order Details] OD ON OD.OrderID = O.OrderID
INNER JOIN Products PROD ON PROD.ProductID = OD.ProductID
GROUP BY
         O.ShipCountry,
         PROD.ProductName
),
TESTE AS
(
 SELECT *
 FROM Products P
 WHERE P.Discontinued = 0
)
SELECT A.PAIS, A.NOME_PRODUTO, A.TOTAL_VENDA
FROM RANKING A
WHERE A.RANKING = 1
ORDER BY A.PAIS

-- CRIE UMA CONSULTA QUE MOSTRE O TOTAL EM ESTOQUE DOS PRODUTOS
--NOME DO PRODUTO, QUANTIDADE, VALOR UNITÁRIO, VALOR TOTAL EM ESTOQUE
-- EXEMPLO: VINHO |50| 10| 500

SELECT PROD.ProductName AS NOME_PRODUTO,
   PROD.UnitsInStock AS QTD,
   PROD.UnitPrice AS VLR_UNITÁRIO,
   PROD.UnitsInStock * PROD.UnitPrice AS QTD_ESTOQUE 
FROM Products PROD
ORDER BY QTD_ESTOQUE DESC

-- CRIE UMA CONSULTA QUE MOSTRE O VENDEDOR TOP 1 POR PAÍS
-- EX: ARGENTINA | ALINE GOMES | 200000

WITH RANKING AS
(
SELECT O.ShipCountry AS PAÍS,
       CONCAT(F.FirstName, '' , F.LastName) AS VENDEDOR,
       ROUND(SUM((OD.Quantity * OD.UnitPrice) * (1 - OD.Discount)),2) AS TOTAL_VENDA,
       -- CRIANDO RANKING ATRAVÉS DA FUNÇÃO ROW_NUMBER():
       ROW_NUMBER()OVER (PARTITION BY O.ShipCountry ORDER BY
       ROUND(SUM((OD.Quantity * OD.UnitPrice) * (1 - OD.Discount)),2) DESC) AS RANKING
FROM Orders O
INNER JOIN Employees F ON F.EmployeeID = O.EmployeeID
INNER JOIN [Order Details] OD ON  O.OrderID = OD.OrderID
GROUP BY O.ShipCountry, CONCAT(F.FirstName, '' , F.LastName)
)
SELECT A.PAÍS, A.VENDEDOR, A.TOTAL_VENDA 
FROM RANKING A
WHERE
   A.RANKING = 1
ORDER BY A.PAÍS

-- CRIE UMA CONSULTA QUE MOSTRE OS 10 PRODUTOS MAIS VENDIDOS PELA EMPRESA EM TODO O MUNDO.
-- ATENÇÃO : É O TOTAL VENDIDO EM NIVEL DE QUANTIDADE DE PRODUTOS
-- EX: VINHO | 5000

SELECT TOP 10 PROD.ProductName AS NOME_PRODUTO,
   SUM(OD.Quantity) AS TOTAL_VENDIDO
FROM [Order Details] OD
INNER JOIN Products PROD ON PROD.ProductID = OD.ProductID
GROUP BY 
  PROD.ProductName
ORDER BY TOTAL_VENDIDO DESC

-- CRIE A MESMA CONSULTA ACIMA MAS AGORA TRAZENDO OS 10 PRODUTOS QUE MAIS FATURARAM

SELECT TOP 10 PROD.ProductName AS NOME_PRODUTO,
       ROUND(SUM((OD.Quantity * OD.UnitPrice) * (1 - OD.Discount)),2) AS TOTAL_VENDA
FROM [Order Details] OD
INNER JOIN Products PROD ON PROD.ProductID = OD.ProductID
GROUP BY 
  PROD.ProductName
ORDER BY TOTAL_VENDA DESC