--1
SELECT * FROM ESTADOS

--2
SELECT * FROM PAIS 
WHERE PAIS.NOME LIKE '%A'

--3
SELECT * FROM MATRICULA
WHERE COD_CURSO != 4

--4
SELECT * 
FROM ALUNOS
WHERE  ALUNOS.IDADE >= 20 AND ALUNOS.IDADE < 30 AND ALUNOS.SEXO = 'F'

--5
SELECT AREA.NOME AS AREA, CURSOS.NOME AS CURSO, ALUNOS.NOME AS ALUNO
FROM CURSOS
INNER JOIN MATRICULA ON MATRICULA.COD_CURSO = CURSOS.COD_CURSO

INNER JOIN AREA ON AREA.COD_AREA = CURSOS.COD_AREA

INNER JOIN ALUNOS ON ALUNOS.CPF = MATRICULA.CPF
ORDER BY ALUNO